# Generated by Django 4.1.1 on 2022-09-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
