# Generated by Django 4.1.1 on 2022-09-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_remove_employee_id_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departent',
            new_name='department',
        ),
    ]
